EXPERIMENT.analysis.MD2.labels = {'topic', 'stoplist', 'stemmer', 'predictor', 'retrievalFunction'};
EXPERIMENT.analysis.MD2.model = eye(5);
EXPERIMENT.analysis.MD2.nested = zeros(5);
EXPERIMENT.analysis.MD2.nested(4, 5) = 1;
EXPERIMENT.analysis.MD2.description = "MD2micro ANOVA";
EXPERIMENT.analysis.MD2.compute = @(data, FACTORS)...
  anovan(...
    data, ...
    EXPERIMENT.analysis.getSelectedFactors(EXPERIMENT.analysis.MD2.labels, FACTORS),... %groups labels
    'model', EXPERIMENT.analysis.MD2.model, ...
    'VarNames', EXPERIMENT.analysis.MD2.labels, ...
    'nested', EXPERIMENT.analysis.MD2.nested, ...
    'sstype', EXPERIMENT.analysis.anova.sstype, ...
    'alpha', EXPERIMENT.analysis.alpha.threshold, ...
    'display', 'off'...
  );


