EXPERIMENT.analysis.MD2qNestedDiff.model = eye(5);
EXPERIMENT.analysis.MD2qNestedDiff.model(6, :) = [0, 1, 0, 0, 1];
EXPERIMENT.analysis.MD2qNestedDiff.model(7, :) = [0, 0, 1, 0, 1];
EXPERIMENT.analysis.MD2qNestedDiff.model(8, :) = [0, 0, 0, 1, 1];
EXPERIMENT.analysis.MD2qNestedDiff.model(9, :) = [0, 1, 1, 0, 0];
EXPERIMENT.analysis.MD2qNestedDiff.model(10, :) = [0, 1, 0, 1, 0];
EXPERIMENT.analysis.MD2qNestedDiff.model(11, :) = [0, 0, 1, 1, 0];

EXPERIMENT.analysis.MD2qNestedDiff.labels = {'topic', 'stoplist', 'stemmer', 'predictor', 'difficulty'};
EXPERIMENT.analysis.MD2qNestedDiff.nested = zeros(5);
EXPERIMENT.analysis.MD2qNestedDiff.nested(1, 5) = 1;

EXPERIMENT.analysis.MD2qNestedDiff.description = "MD2qNestedDiffmicro ANOVA";
EXPERIMENT.analysis.MD2qNestedDiff.compute = @(data, FACTORS)...
  anovan(...
    data, ...
    {FACTORS.topic, FACTORS.stoplist, FACTORS.stemmer, FACTORS.predictor, FACTORS.difficulty}, ... %groups labels
    'model', EXPERIMENT.analysis.MD2qNestedDiff.model, ...
    'nested', EXPERIMENT.analysis.MD2qNestedDiff.nested, ...
    'VarNames', EXPERIMENT.analysis.MD2qNestedDiff.labels, ...
    'sstype', EXPERIMENT.analysis.anova.sstype, ...
    'alpha', EXPERIMENT.analysis.alpha.threshold, ...
    'display', 'off'...
  );


