EXPERIMENT.analysis.MD0.model = [eye(4)];
EXPERIMENT.analysis.MD0.labels = {'topic', 'stoplist', 'stemmer', 'predictor'};
EXPERIMENT.analysis.MD0.description = "MD0micro ANOVA";
EXPERIMENT.analysis.MD0.compute = @(data, FACTORS)...
  anovan(...
    data, ...
    EXPERIMENT.analysis.getSelectedFactors(EXPERIMENT.analysis.MD0.labels, FACTORS),... %groups labels
    'model', EXPERIMENT.analysis.MD0.model, ...
    'VarNames', EXPERIMENT.analysis.MD0.labels, ...
    'sstype', EXPERIMENT.analysis.anova.sstype, ...
    'alpha', EXPERIMENT.analysis.alpha.threshold, ...
    'display', 'off'...
  );


