EXPERIMENT.analysis.MD1.labels = {'query', 'topic', 'stoplist', 'stemmer', 'predictor'};
EXPERIMENT.analysis.MD1.model = eye(length(EXPERIMENT.analysis.MD1.labels));
EXPERIMENT.analysis.MD1.nested = zeros(length(EXPERIMENT.analysis.MD1.labels));
EXPERIMENT.analysis.MD1.nested(1, 2) = 1;
EXPERIMENT.analysis.MD1.description = "MD1micro ANOVA";


EXPERIMENT.analysis.MD1.compute = @(data, FACTORS)...
  anovan(...
    data, ...
    EXPERIMENT.analysis.getSelectedFactors(EXPERIMENT.analysis.MD1.labels, FACTORS), ... %groups labels
    'model', EXPERIMENT.analysis.MD1.model, ...
    'nested', EXPERIMENT.analysis.MD1.nested, ...
    'VarNames', EXPERIMENT.analysis.MD1.labels, ...
    'sstype', EXPERIMENT.analysis.anova.sstype, ...
    'alpha', EXPERIMENT.analysis.alpha.threshold, ...
    'display', 'off'...
  );



