EXPERIMENT.analysis.MDqNestedDiff.model = eye(5);
EXPERIMENT.analysis.MDqNestedDiff.labels = {'topic', 'stoplist', 'stemmer', 'predictor', 'difficulty'};
EXPERIMENT.analysis.MDqNestedDiff.nested = zeros(5);
EXPERIMENT.analysis.MDqNestedDiff.nested(1, 5) = 1;
EXPERIMENT.analysis.MDqNestedDiff.description = "MDqNestedDiffmicro ANOVA";
EXPERIMENT.analysis.MDqNestedDiff.compute = @(data, FACTORS)...
  anovan(...
    data, ...
    {FACTORS.topic, FACTORS.stoplist, FACTORS.stemmer, FACTORS.predictor, FACTORS.difficulty}, ... %groups labels
    'model', EXPERIMENT.analysis.MDqNestedDiff.model, ...
    'nested', EXPERIMENT.analysis.MDqNestedDiff.nested, ...
    'VarNames', EXPERIMENT.analysis.MDqNestedDiff.labels, ...
    'sstype', EXPERIMENT.analysis.anova.sstype, ...
    'alpha', EXPERIMENT.analysis.alpha.threshold, ...
    'display', 'off'...
  );


